### ISSUE TITLE
有没有其他语音质量评估方法？

### ISSUE THREAD

**Issue by zuowanbushiwo** [YongyuG/dnn_aec_data_process#3]
你好 ,
有一个问题想请教一下，现在有比较好的无参考信号的评估语音增强后语音质量的方法吗？ 
我看AEC-Challenge 是使用的基于web api 的mos，有没有离线的吗？而PESQ是需要参考信号。
参加 AEC-Challenge 的最后结果会公布吗？可以得到他们众包mos测试的结果和相应的语音源文件吗？

**Comment by YongyuG** [comment]
> 你好 ,
> 有一个问题想请教一下，现在有比较好的无参考信号的评估语音增强后语音质量的方法吗？
> 我看AEC-Challenge 是使用的基于web api 的mos，有没有离线的吗？而PESQ是需要参考信号。
> 参加 AEC-Challenge 的最后结果会公布吗？可以得到他们众包mos测试的结果和相应的语音源文件吗？

aec-challeng已经公布了噢，他们的所有数据都能拿到的，你可以去下载试试看
至于无参考信号的语音质量评测的话，一是可以用他们的，二是你可以自己再训一个做质检的模型，或者你就用仿真的测erle就好啦

**Comment by zuowanbushiwo** [comment]
好的，谢谢！
