### ISSUE TITLE
Nonlinear simulate maybe error.

### ISSUE THREAD

**Issue by TeaPoly** [YongyuG/dnn_aec_data_process#5]
https://github.com/YongyuG/dnn_aec_data_process/blob/71083bce4f12e7cdd20888c4067ffa306c5f9c34/timit_pre_process.py#L190

I think it should be negative here. [DNN-based residual echo suppression](https://www.isca-speech.org/archive/interspeech_2015/lee15g_interspeech.html)

![](https://static01.imgkr.com/temp/e6df9de97de2409baa1d13993d1c4207.png)

**Comment by YongyuG** [comment]
> https://github.com/YongyuG/dnn_aec_data_process/blob/71083bce4f12e7cdd20888c4067ffa306c5f9c34/timit_pre_process.py#L190
> 
> I think it should be negative here. [DNN-based residual echo suppression](https://www.isca-speech.org/archive/interspeech_2015/lee15g_interspeech.html)
> 
> ![](https://camo.githubusercontent.com/0cbccadf64d916b683d34fdf96dea843fd11fbe2914db1d1aae5b5033d3e0069/68747470733a2f2f73746174696330312e696d676b722e636f6d2f74656d702f65366466396465393764653234303962616131643133393933643163343230372e706e67)

yes ur are right, there are few silly mistakes,
